---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-webhook
  namespace: nukleros-secrets-system # +operator-builder:field:name=namespace,default="nukleros-secrets-system",type=string
  labels:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: v0.5.9 # +operator-builder:field:name=version,default="v0.5.9",type=string
    external-secrets.io/component: webhook
    platform.nukleros.io/group: secrets
    platform.nukleros.io/project: external-secrets
