commonOverlays:
  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
    value: "%v"  # +operator-builder:field:name=namespace,default="%v",type=string

yamlFiles:
  - name: "external-dns config for active directory"
    path: "../vendor/config-active-directory.yaml"
    outputPath: "manifests/config-active-directory.yaml"
    overlays:
      - name: "add include marker for active directory secret and configmap"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="active-directory",include
          apiVersion: v1

  - name: "external-dns config for google"
    path: "../vendor/config-google.yaml"
    outputPath: "manifests/config-google.yaml"
    overlays:
      - name: "add include marker for google secret and configmap"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="google",include
          apiVersion: v1

  - name: "external-dns config for route53"
    path: "../vendor/config-route53.yaml"
    outputPath: "manifests/config-route53.yaml"
    overlays:
      - name: "add include marker for route53 secret and configmap"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="route53",include
          apiVersion: v1

      - name: "set domain name for hosted zone in route53"
        query: "stringData"
        value:
          EXTERNAL_DNS_DOMAIN_FILTER: nukleros.io # +operator-builder:field:name=domainName,type=string

      - name: "set domain hosted zone type in route53"
        query: "stringData"
        value:
          # +operator-builder:field:name=externalDNS.zoneType,default="%v",type=string,description=`
          # +kubebuilder:validation:Enum=private;public
          # Type of DNS hosted zone to manage.`
          EXTERNAL_DNS_AWS_ZONE_TYPE: private

  - name: "external-dns deployment for active directory"
    path: "../vendor/deployment-active-directory.yaml"
    outputPath: "manifests/deployment-active-directory.yaml"
    overlays:
      - name: "add include marker for active directory deployment"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="active-directory",include
          apiVersion: apps/v1

      - name: "add external-dns deployment replica count marker"
        value:
          spec:
            # +operator-builder:field:name=externalDNS.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the external-dns deployment.`
            replicas: !!int "%v"

      - name: "add external-dns image markers"
        query: "spec.template.spec.containers[?(@.name == 'external-dns')]"
        value:
          # +operator-builder:field:name=externalDNS.image,default={{ .defaultImage }},type=string,replace="externalDNSImage",description=`
          # Image repo and name to use for external-dns.`
          # +operator-builder:field:name=externalDNS.version,default={{ .defaultVersion }},type=string,replace="externalDNSVersion",description=`
          # Version of external-dns to use.`
          image: externalDNSImage:externalDNSVersion

  - name: "external-dns deployment for google"
    path: "../vendor/deployment-google.yaml"
    outputPath: "manifests/deployment-google.yaml"
    overlays:
      - name: "add include marker for google deployment"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="google",include
          apiVersion: apps/v1

      - name: "add external-dns deployment replica count marker"
        value:
          spec:
            # +operator-builder:field:name=externalDNS.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the external-dns deployment.`
            replicas: !!int "%v"

      - name: "add external-dns image markers"
        query: "spec.template.spec.containers[?(@.name == 'external-dns')]"
        value:
          # +operator-builder:field:name=externalDNS.image,default={{ .defaultImage }},type=string,replace="externalDNSImage"
          # +operator-builder:field:name=externalDNS.version,default={{ .defaultVersion }},type=string,replace="externalDNSVersion"
          image: externalDNSImage:externalDNSVersion

  - name: "external-dns deployment for route53"
    path: "../vendor/deployment-route53.yaml"
    outputPath: "manifests/deployment-route53.yaml"
    overlays:
      - name: "add include marker for route53 deployment"
        query: "$"
        value:
          # +operator-builder:resource:field=externalDNS.provider,value="route53",include
          apiVersion: apps/v1

      - name: "add external-dns deployment replica count marker"
        value:
          spec:
            # +operator-builder:field:name=externalDNS.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the external-dns deployment.`
            replicas: !!int "%v"

      - name: "add external-dns image markers"
        query: "spec.template.spec.containers[?(@.name == 'external-dns')]"
        value:
          # +operator-builder:field:name=externalDNS.image,default={{ .defaultImage }},type=string,replace="externalDNSImage"
          # +operator-builder:field:name=externalDNS.version,default={{ .defaultVersion }},type=string,replace="externalDNSVersion"
          image: externalDNSImage:externalDNSVersion

  - name: "external-dns rbac"
    path: "../vendor/rbac.yaml"
    outputPath: "manifests/rbac.yaml"
    overlays:
      - name: "add include marker for route53 deployment"
        documentQuery:
          - conditions:
            - query: $[?($.kind == "ServiceAccount")]
        query: "metadata"
        value:
          annotations:
            # +operator-builder:field:name=externalDNS.iamRoleArn,type=string,description=`
            # On AWS, the IAM Role ARN that gives external-dns access to Route53`
            eks.amazonaws.com/role-arn: iam_role_arn

      - name: "set name of service account which is referenced in role policy doc for AWS"
        documentQuery:
          - conditions:
            - query: $[?($.kind == "ServiceAccount")]
        query: "metadata"
        value:
          # +operator-builder:field:name=externalDNS.serviceAccountName,default=external-dns,type=string,description=`
          # The name of the external-dns service account which is referenced in role policy doc for AWS.`
          name: external-dns

