---
# +operator-builder:resource:field=provider,value="route53",include
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-route53
  namespace: nukleros-gateway-system # +operator-builder:field:name=namespace,default="nukleros-gateway-system",type=string
  labels:
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
stringData:
  EXTERNAL_DNS_TXT_OWNER_ID: external-dns-
  EXTERNAL_DNS_TXT_PREFIX: external-dns-
  EXTERNAL_DNS_PROVIDER: aws
  # +operator-builder:field:name=zoneType,default="private",type=string,description=`
  # +kubebuilder:validation:Enum=private;public
  # Type of DNS hosted zone to manage.`
  EXTERNAL_DNS_AWS_ZONE_TYPE: private
  EXTERNAL_DNS_DOMAIN_FILTER: nukleros.io # +operator-builder:field:name=domainName,type=string
  EXTERNAL_DNS_POLICY: sync
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
