---
# +operator-builder:resource:field=provider,value="active-directory",include
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-active-directory
  labels:
    app: external-dns-active-directory
    app.kubernetes.io/name: external-dns-active-directory
    app.kubernetes.io/instance: external-dns
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: external-dns
  namespace: nukleros-gateway-system # +operator-builder:field:name=namespace,default="nukleros-gateway-system",type=string
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-active-directory
  template:
    metadata:
      labels:
        app: external-dns-active-directory
        app.kubernetes.io/name: external-dns-active-directory
        app.kubernetes.io/instance: external-dns
        platform.nukleros.io/group: ingress
        platform.nukleros.io/project: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          # +operator-builder:field:name=image,default=k8s.gcr.io/external-dns/external-dns,type=string,replace="externalDNSImage",description=`
          # Image repo and name to use for external-dns.`
          # +operator-builder:field:name=version,default=v0.12.2,type=string,replace="externalDNSVersion",description=`
          # Version of external-dns to use.`
          image: externalDNSImage:externalDNSVersion
          args:
            - --source=service
            - --source=ingress
            - --registry=txt
          envFrom:
            - secretRef:
                name: external-dns-active-directory
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: external-dns-active-directory-kerberos
              subPath: krb5.conf
              mountPath: /etc/krb5.conf
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
      volumes:
        - name: external-dns-active-directory-kerberos
          configMap:
            defaultMode: 420
            name: external-dns-active-directory-kerberos
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - external-dns-active-directory
  replicas: 1
