---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    platform.nukleros.io/category: ingress
    platform.nukleros.io/project: nginx-ingress-controller
spec:
  controller: nginx.org/ingress-controller
