---
# +operator-builder:resource:field=nginx.include,value=true,include
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: nginx-ingress-controller
spec:
  controller: nginx.org/ingress-controller
