---
# +operator-builder:resource:field=nginx.include,value=true,include
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-gcp-azure
  namespace: nukleros-ingress-system # +operator-builder:field:name=namespace,default="nukleros-ingress-system",type=string
  labels:
    platform.nukleros.io/group: ingress
    platform.nukleros.io/project: nginx-ingress-controller
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: nginx-ingress
