apiVersion: ingress.support-services.nukleros.io/v1alpha1
kind: GlooEdge
metadata:
  name: glooedge-sample
spec:
  #collection:
    #name: "supportservices-sample"
    #namespace: ""
  ports:
    - name: http
      port: 80
      ssl: false
    - name: https
      port: 443
      ssl: true
