---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: kong-serviceaccount
  name: kong-serviceaccount-token
  namespace: nukleros-ingress-system # +operator-builder:field:name=namespace,default="nukleros-ingress-system",type=string
  labels:
    platform.nukleros.io/category: ingress
    platform.nukleros.io/project: kong-ingress-controller
type: kubernetes.io/service-account-token
