commonOverlays:
  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
    value: "%v"  # +operator-builder:field:name=namespace,default="%v",type=string

yamlFiles:
  - name: "cert-manager crds"
    path: "../vendor/crds.yaml"
    outputPath: "manifests/crds.yaml"

  - name: "cert-manager cainjector deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add cainjector replica count marker"
        query: "$[?($.metadata.name == 'cert-manager-cainjector')]"
        value:
          spec:
            # +operator-builder:field:name=certManager.cainjector.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the cert-manager cainjector deployment.`
            replicas: !!int "%v"

      - name: "add cainjector image name markers"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "cert-manager-cainjector")]
        query: "spec.template.spec.containers[?(@.name == 'cert-manager')]"
        value:
          # +operator-builder:field:name=certManager.cainjector.image,default={{ .defaultCainjectorImage }},type=string,replace="cainjectorImage",description=`
          # Image repo and name to use for cert-manager cainjector.`
          # +operator-builder:field:name=certManager.version,default={{ .defaultVersion }},type=string,replace="certManagerVersion",description=`
          # Version of cert-manager to use.`
          image: cainjectorImage:certManagerVersion

  - name: "cert-manager controller deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add controller replica count marker"
        query: "$[?($.metadata.name == 'cert-manager')]"
        value:
          spec:
            # +operator-builder:field:name=certManager.controller.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the cert-manager controller deployment.`
            replicas: !!int "%v"

      - name: "add controller image name markers"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "cert-manager")]
        query: "spec.template.spec.containers[?(@.name == 'cert-manager')]"
        value:
          # +operator-builder:field:name=certManager.controller.image,default={{ .defaultControllerImage }},type=string,replace="controllerImage",description=`
          # Image repo and name to use for cert-manager controller.`
          # +operator-builder:field:name=certManager.version,default={{ .defaultVersion }},type=string,replace="certManagerVersion"
          image: controllerImage:certManagerVersion

  - name: "cert-manager webhook deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add webhook replica count marker"
        query: "$[?($.metadata.name == 'cert-manager-webhook')]"
        value:
          spec:
            # +operator-builder:field:name=certManager.webhook.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the cert-manager webhook deployment.`
            replicas: !!int "%v"

      - name: "add webhook image name markers"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "cert-manager-webhook")]
        query: "spec.template.spec.containers[?(@.name == 'cert-manager')]"
        value:
          # +operator-builder:field:name=certManager.webhook.image,default={{ .defaultWebhookImage }},type=string,replace="webhookImage",description=`
          # Image repo and name to use for cert-manager webhook.`
          # +operator-builder:field:name=certManager.version,default={{ .defaultVersion }},type=string,replace="certManagerVersion"
          image: webhookImage:certManagerVersion

  - name: "cert-manager rbac"
    path: "../vendor/rbac.yaml"
    outputPath: "manifests/rbac.yaml"

  - name: "cert-manager service"
    path: "../vendor/service.yaml"
    outputPath: "manifests/service.yaml"

  - name: "cert-manager webhook"
    path: "../vendor/webhook.yaml"
    outputPath: "manifests/webhook.yaml"

  - name: "cert-manager cluster issuer"
    path: "../static/issuer.yaml"
    outputPath: "manifests/issuer.yaml"
    overlays:
      - name: "add include marker for non-prod issuer"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "letsencrypt-staging")]
        query: "$"
        value:
          # +operator-builder:resource:collectionField=tier,value="production",include=false
          apiVersion: cert-manager.io/v1

      - name: "add include marker for prod issuer"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "letsencrypt-production")]
        query: "$"
        value:
          # +operator-builder:resource:collectionField=tier,value="production",include
          apiVersion: cert-manager.io/v1

      - name: "add contact email"
        query: "spec.acme"
        value:
          # +operator-builder:field:name=certManager.contactEmail,type=string,description=`
          # Contact e-mail address for receiving updates about certificates from LetsEncrypt.`
          email: admin@nukleros.io

