# permissions for end users to edit supportservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: supportservices-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: support-services-operator
    app.kubernetes.io/part-of: support-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: supportservices-editor-role
rules:
- apiGroups:
  - orchestration.support-services.nukleros.io
  resources:
  - supportservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orchestration.support-services.nukleros.io
  resources:
  - supportservices/status
  verbs:
  - get
