# permissions for end users to edit supportservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supportservices-editor-role
rules:
- apiGroups:
  - setup.addons.nukleros.io
  resources:
  - supportservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - setup.addons.nukleros.io
  resources:
  - supportservices/status
  verbs:
  - get
