---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-authority
  namespace: nukleros-gateway-system # +operator-builder:field:name=namespace,default="nukleros-gateway-system",type=string
spec:
  isCA: true
  commonName: gloo-edge
  secretName: certificate-authority
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io