apiVersion: platform.addons.nukleros.io/v1alpha1
kind: IngressComponent
metadata:
  name: ingresscomponent-sample
spec:
  #collection:
    #name: "supportservices-sample"
    #namespace: ""
  nginx:
    installType: "deployment"
    include: false
    image: "nginx/nginx-ingress"
    version: "2.3.0"
    replicas: 2
  kong:
    include: true
    replicas: 2
    gateway:
      image: "kong/kong-gateway"
      version: "2.8"
    ingressController:
      image: "kong/kubernetes-ingress-controller"
      version: "2.5.0"
  externalDNS:
    provider: "none"
    image: "k8s.gcr.io/external-dns/external-dns"
    version: "v0.12.2"
    serviceAccountName: "external-dns"
    iamRoleArn: "iam_role_arn"
  namespace: "nukleros-ingress-system"
  domainName: "nukleros.io"
