apiVersion: secrets.support-services.nukleros.io/v1alpha1
kind: ExternalSecrets
metadata:
  name: externalsecrets-sample
spec:
  #collection:
    #name: "supportservices-sample"
    #namespace: ""
  namespace: "nukleros-secrets-system"
  version: "v0.5.9"
  certController:
    replicas: 1
  image: "ghcr.io/external-secrets/external-secrets"
  controller:
    replicas: 2
  webhook:
    replicas: 2
