---
# +operator-builder:field:name=tier,arbitrary,default="local",type=string,description=`
# +kubebuilder:validation:Enum=local;development;production
# The tier of cluster being used.  One of: local | development | production.`
apiVersion: v1
kind: Namespace
metadata:
  name: nukleros-support-services-system  # +operator-builder:field:parent=metadata.name,type=string
