---
# +operator-builder:field:name=nginx.installType,arbitrary,default="deployment",type=string,description=`
# +kubebuilder:validation:Enum=deployment;daemonset
# Method of install nginx ingress controller.  One of: deployment | daemonset.`
# +operator-builder:field:name=nginx.include,arbitrary,default=false,type=bool,description=`
# Include the Nginx ingress controller when installing ingress components.`
# +operator-builder:field:name=kong.include,arbitrary,default=true,type=bool,description=`
# Include the Kong ingress controller when installing ingress components.`
# +operator-builder:field:name=externalDNS.provider,arbitrary,default=none,type=string,description=`
# +kubebuilder:validation:Enum=none;active-directory;google;route53
# The DNS provider to use for setting DNS records with external-dns.  One of: none | active-directory | google | route53.`
apiVersion: v1
kind: Namespace
metadata:
  # +operator-builder:field:name=namespace,default="nukleros-ingress-system",type=string,description=`
  # Namespace to use for ingress support services.`
  name: nukleros-ingress-system
  labels:
    externalDNSProvider: none # +operator-builder:field:name=externalDNS.provider,type=string
