commonOverlays:
  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
    value: "%v"  # +operator-builder:field:name=namespace,default="%v",type=string

yamlFiles:
  - name: "nginx configmap"
    path: "../vendor/config.yaml"
    outputPath: "manifests/config.yaml"

  - name: "nginx crds"
    path: "../vendor/crds.yaml"
    outputPath: "manifests/crds.yaml"

  - name: "nginx daemonset"
    path: "../vendor-nginx/nginx-ingress.yaml"
    outputPath: "manifests/daemonset.yaml"
    overlays:
      - name: "add namespace markers minus default"
        query:
          - metadata.namespace
        value: "%v"  # +operator-builder:field:name=namespace,type=string

      - name: "add include marker for nginx daemonset"
        query: "$"
        value:
          # +operator-builder:resource:field=nginx.installType,value="daemonset",include
          apiVersion: apps/v1

      - name: "add nginx ingress controller image markers"
        query: "spec.template.spec.containers[?(@.name == 'nginx-ingress')]"
        value:
          # +operator-builder:field:name=nginx.image,default={{ .defaultImage }},type=string,replace="nginxImage",description=`
          # Image repo and name to use for nginx.`
          # +operator-builder:field:name=nginx.version,default="{{ .defaultVersion }}",type=string,replace="nginxVersion",description=`
          # Version of nginx to use.`
          image: nginxImage:nginxVersion

  - name: "nginx deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add include marker for nginx deployment"
        query: "$"
        value:
          # +operator-builder:resource:field=nginx.installType,value="deployment",include
          apiVersion: apps/v1

      - name: "add nginx ingress controller image markers"
        query: "spec.template.spec.containers[?(@.name == 'nginx-ingress')]"
        value:
          # +operator-builder:field:name=nginx.image,default={{ .defaultImage }},type=string,replace="nginxImage",description=`
          # Image repo and name to use for nginx.`
          # +operator-builder:field:name=nginx.version,default="{{ .defaultVersion }}",type=string,replace="nginxVersion",description=`
          # Version of nginx to use.`
          image: nginxImage:nginxVersion

      - name: "add nginx ingress controller replica count marker"
        query: "$"
        value:
          spec:
            # +operator-builder:field:name=nginx.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the nginx ingress controller deployment.`
            replicas: !!int "%v"

  - name: "nginx ingress class"
    path: "../vendor/ingress-class.yaml"
    outputPath: "manifests/ingress-class.yaml"

  - name: "nginx rbac"
    path: "../vendor/rbac.yaml"
    outputPath: "manifests/rbac.yaml"
    overlays:
      - name: "add namespace markers minus default"
        query:
          - metadata.namespace
          - subjects[*].namespace
        value: "%v"  # +operator-builder:field:name=namespace,type=string

  - name: "nginx service for aws"
    path: "../vendor/service-aws.yaml"
    outputPath: "manifests/service-aws.yaml"

  - name: "nginx service for gcp and azure"
    path: "../vendor/service-gcp-azure.yaml"
    outputPath: "manifests/service-gcp-azure.yaml"

  - name: "nginx default server certificate"
    path: "../static/cert.yaml"
    outputPath: "manifests/cert.yaml"
    overlays:
      - name: "add include marker for local cert"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "nginx-default-server-secret-local")]
        query: "$"
        value:
          # +operator-builder:resource:collectionField=tier,value="local",include
          apiVersion: cert-manager.io/v1

      - name: "add include marker for non-prod cert"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "nginx-default-server-secret-non-prod")]
        query: "$"
        value:
          # +operator-builder:resource:collectionField=tier,value="development",include
          apiVersion: cert-manager.io/v1

      - name: "add include marker for prod cert"
        documentQuery:
          - conditions:
            - query: $[?($.metadata.name == "nginx-default-server-secret-prod")]
        query: "$"
        value:
          # +operator-builder:resource:collectionField=tier,value="production",include
          apiVersion: cert-manager.io/v1

      - name: "add domain name for ingress cert"
        query: "spec.dnsNames"
        action: replace
        value:
          - nukleros.io  # +operator-builder:field:name=domainName,type=string

