---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: secret-reloader
    platform.nukleros.io/group: secrets
    platform.nukleros.io/project: reloader
  name: secret-reloader
  namespace: nukleros-secrets-system # +operator-builder:field:name=namespace,default="nukleros-secrets-system",type=string
spec:
  # +operator-builder:field:name=replicas,default="1",type=int,description=`
  # Number of replicas to use for the reloader deployment.`
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-reloader
      platform.nukleros.io/group: secrets
      platform.nukleros.io/project: reloader
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-reloader
        platform.nukleros.io/group: secrets
        platform.nukleros.io/project: reloader
    spec:
      containers:
        - # +operator-builder:field:name=image,default=stakater/reloader,type=string,replace="reloaderImage",description=`
          # Image repo and name to use for `
          # +operator-builder:field:name=version,default="v0.0.119",type=string,replace="reloaderVersion",description=`
          # Version of reloader to use.`
          image: reloaderImage:reloaderVersion
          imagePullPolicy: IfNotPresent
          name: secret-reloader
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsUser: 65534
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: secret-reloader
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - reloader
      nodeSelector:
        kubernetes.io/os: linux
