name: threeport-workload-controller Release

on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/nukleros/*
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.1
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19

    - name: Configure git to access private repos
      run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Test
      run: make test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean -f  ./.goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
